modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/honk/issues"

[[mods]]
modId = "honk"
version = "${file.jarVersion}"
displayName = "Honk"
displayURL="https://github.com/JamCoreModding/honk"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Meet the Honk - a mysterious prehistoric creature extinct for years...until now.
'''

[[dependencies.honk]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.honk]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.honk]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.honk]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "honk.mixins.json"
